# Generated by Django 5.2.5 on 2025-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_date_joined_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачено"),
                    ("failed", "Ошибка оплаты"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID цены в Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID продукта в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID сессии в Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
