# Generated by Django 5.2.5 on 2025-09-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
